services:

  postgres:
    image: debezium/example-postgres:2.7.3.Final
    container_name: postgres
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env.docker

  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    hostname: schema-registry
    container_name: schema-registry
    ports:
      - "8082:8082"
    depends_on:
      - kafka
    networks:
      - default
    env_file:
      - .env.docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/subjects"]
      interval: 30s
      timeout: 10s
      retries: 5

  debezium:
    image: debezium/connect:3.0.0.Final
    container_name: debezium
    ports:
      - "8083:8083"
    env_file:
      - .env.docker
    depends_on:
      - schema-registry
    volumes:
      - ./avro-converter:/kafka/connect/avro-converter
      - ./s3-connector:/kafka/connect/s3-connector

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "29092:29092"
      - "9092:9092"
    env_file:
      - .env.docker
    healthcheck:
      test: [ "CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092" ]
      interval: 10s
      timeout: 5s
      retries: 5 